name: "CICD for ecorm frontend"
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Echo "Hello, World!"
        run: echo "Hello World!"

